export const actionTypes = {
  SET_FAVORITES: "SET_FAVORITES",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  SET_OWNED: "SET_OWNED",
  ADD_OWNED: "ADD_OWNED",
  REMOVE_OWNED: "REMOVE_OWNED",
};
